version: '3'

services:
  portainer:
    image: portainer/agent:latest
    container_name: portainer_agent
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "portainer-agent"
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "telegraf"
    user: "telegraf:${DOCKER_GROUP}"
    group_add:
      - "${DOCKER_GROUP}"
      - "${PGID}"
    hostname: $COM_OBSIDIAN_HOST
    ports:
      - 57100:57100
      - 57500:57500
    environment:
      COM_OBSIDIAN_HOST: "${COM_OBSIDIAN_HOST}"
      COM_OBSIDIAN_SERVICE: "host"
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      INFLUXDB_TELEGRAF_TOKEN: "${INFLUXDB_TELEGRAF_TOKEN}"
      INFLUXDB_URL: "${INFLUXDB_URL}"
      INFLUXDB_BUCKET: "telemetry"
      INFLUXDB_ORG: "org"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
  gitlab_runner:
    build:
      context: ./gitlab_runner
    container_name: gitlab_runner
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "gitlab-runner"
    group_add:
      - "${PGID}"
    volumes:
      - gitlab-runner-data:/etc/gitlab-runner/
      - ./gitlab_runner/config.toml:/etc/gitlab-runner/config.toml
volumes:
  gitlab-runner-data:
networks:
  db-net:

