server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: ${COM_OBSIDIAN_LOKI_URL}

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.compose.project=${COM_OBSIDIAN_HOST}"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_obsidian_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_obsidian_host']
        target_label: 'host'
