server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://docker-monitoring:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.compose.project=docker-media"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_obsidian_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_obsidian_host']
        target_label: 'host'
