version: "3.2"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${DATA_DIR}/portainer/data:/data
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ${INFLUXDB_DATA}:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telemetry
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=admin
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  grafana:
    image: grafana/grafana:latest
    user: "${PUID}:${PGID}"
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/grafana/provisioning:/etc/grafana/provisioning
      - ${DATA_DIR}/grafana/storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    user: "$PUID:${DOCKER_GROUP}"
    group_add:
      - "${DOCKER_GROUP}"
    hostname: docker-monitoring
    ports:
      - 57100:57100
      - 57500:57500
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
