version: "3.2"
name: docker-monitoring
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "portainer"
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${DATA_DIR}/portainer/data:/data
  influxdb:
    image: influxdb:2.5-alpine
    container_name: influxdb
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "influxdb"
    group_add:
      - "${PGID}"
    ports:
      - 8086:8086
    volumes:
      - ${INFLUXDB_DATA}:/var/lib/influxdb2
      - ./influxdb/influxdb.conf:/etc/influxdb2/influxdb.conf
      - ./influxdb/influx_init.sh:/docker-entrypoint-initdb.d/influx_init.sh
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=passwordpassword
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
  influxdb18:
    image: influxdb:1.8.10-alpine
    container_name: influxdb18
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "influxdb18"
    group_add:
      - "${PGID}"
    ports:
      - 9457:8086
    volumes:
      - ${INFLUXDB18_DATA}:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=varken
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=admin
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  grafana:
    image: grafana/grafana:latest
    user: "${PUID}:${PGID}"
    container_name: grafana
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "grafana"
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/grafana/provisioning:/etc/grafana/provisioning
      - ${DATA_DIR}/grafana/storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb
      - influxdb18
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - COM_OBSIDIAN_HOST_IP=${COM_OBSIDIAN_HOST_IP}
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "telegraf"
    user: "telegraf:${DOCKER_GROUP}"
    group_add:
      - "${DOCKER_GROUP}"
    hostname: $COM_OBSIDIAN_HOST
    ports:
      - 57100:57100
      - 57500:57500
    environment:
      COM_OBSIDIAN_HOST: "${COM_OBSIDIAN_HOST}"
      COM_OBSIDIAN_SERVICE: "host"
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      HOST_MOUNT_PREFIX: /rootfs
      INFLUXDB_TELEGRAF_TOKEN: "${INFLUXDB_TELEGRAF_TOKEN}"
      INFLUXDB_URL: "${INFLUXDB_URL}"
      INFLUXDB_BUCKET: "telemetry"
      INFLUXDB_ORG: "org"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
      - /mnt/0:/rootfs/mnt/0
      - /mnt/1:/rootfs/mnt/1
      - /mnt/2:/rootfs/mnt/2
      - /mnt/3:/rootfs/mnt/3
  loki:
    image: grafana/loki:2.7.1
    container_name: loki
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "loki"
    ports:
      - 3100:3100
    group_add:
      - "${PGID}"
    volumes:
      - ${LOKI_DATA}:/loki
  prometheus:
    image: prom/prometheus:v2.40.7
    container_name: prometheus
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "prometheus"
    group_add:
      - "${PGID}"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_DATA}:/prometheus
