version: "3.2"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${DATA_DIR}/portainer/data:/data
  influxdb:
    image: influxdb:2.5-alpine
    container_name: influxdb
    group_add:
      - "${PGID}"
    ports:
      - 8086:8086
    volumes:
      - ${INFLUXDB_DATA}:/var/lib/influxdb2
      - ./influxdb/influxdb.conf:/etc/influxdb2/influxdb.conf
      - ./influxdb/influx_init.sh:/docker-entrypoint-initdb.d/influx_init.sh
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=passwordpassword
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
  grafana:
    image: grafana/grafana:latest
    user: "${PUID}:${PGID}"
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/grafana/provisioning:/etc/grafana/provisioning
      - ${DATA_DIR}/grafana/storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    user: "telegraf:${DOCKER_GROUP}"
    group_add:
      - "${DOCKER_GROUP}"
    hostname: docker-monitoring
    ports:
      - 57100:57100
      - 57500:57500
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      INFLUXDB_TELEGRAF_TOKEN: "${INFLUXDB_TELEGRAF_TOKEN}"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
  loki:
    image: grafana/loki:2.7.1
    container_name: loki
    ports:
      - 3100:3100
    group_add:
      - "${PGID}"
    volumes:
      - ${LOKI_DATA}:/loki
  prometheus:
    image: prom/prometheus:v2.40.7
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_DATA}:/prometheus
