version: "3.2"
services:
  portainer:
    image: portainer/agent:latest
    container_name: portainer_agent
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/lidarr/config:/config
      - ${VOLUME_1}:/mnt/0
      - ${DOWNLOAD_DIR}:/RAID10Plex/transmission/completed
    ports:
      - 8686:8686
    restart: unless-stopped
