version: "3.2"
name: docker-media
services:
  portainer:
    image: portainer/agent:latest
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "portainer-agent"
    container_name: portainer_agent
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "telegraf"
    user: "telegraf:${DOCKER_GROUP}"
    group_add:
      - "${DOCKER_GROUP}"
      - "${PGID}"
    hostname: $COM_OBSIDIAN_HOST
    ports:
      - 57100:57100
      - 57500:57500
    environment:
      COM_OBSIDIAN_HOST: "${COM_OBSIDIAN_HOST}"
      COM_OBSIDIAN_SERVICE: "host"
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      INFLUXDB_TELEGRAF_TOKEN: "${INFLUXDB_TELEGRAF_TOKEN}"
      INFLUXDB_URL: "${INFLUXDB_URL}"
      INFLUXDB_BUCKET: "telemetry"
      INFLUXDB_ORG: "org"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
  promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "promtail"
    group_add:
      - "${DOCKER_GROUP}"
      - "${PGID}"
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    environment:
      COM_OBSIDIAN_HOST: "${COM_OBSIDIAN_HOST}"
      COM_OBSIDIAN_LOKI_URL: "${PROMTAIL_LOKI_URL}"
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "lidarr"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/lidarr/config:/config
      - ${LIDARR_VOLUME_1}:/music
      - ${DOWNLOAD_HOST_DIR}:${DOWNLOAD_QBITTORRENT_DIR}
    ports:
      - 8686:8686
  radarr_4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr_4k
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "radarr-4k"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/radarr/config:/config
      - ${RADARR_4K_VOLUME_1}:/movies
      - ${DOWNLOAD_HOST_DIR}:${DOWNLOAD_QBITTORRENT_DIR}
    ports:
      - 7878:7878
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "prowlarr"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/prowlarr/config:/config
    ports:
      - 9696:9696
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "bazarr"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/bazarr/config:/config
      - ${SONARR_VOLUME_1}:/mnt/tv_shows1
      - ${SONARR_VOLUME_2}:/mnt/tv_show2
      - ${RADARR_VOLUME_1}:/mnt/movies1
      - ${RADARR_VOLUME_2}:/mnt/movies2
    ports:
      - 6767:6767
  bazarr_4k:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr_4k
    labels:
      com.obsidian.host: "${COM_OBSIDIAN_HOST}"
      com.obsidian.service: "bazarr-4k"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/bazarr_4k/config:/config
      - ${RADARR_4K_VOLUME_1}:/mnt/movies1
    ports:
      - 6768:6767
