global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "qbittorrent_exporter"
    static_configs:
      - targets: ['docker-media-watcher:59571']
  - job_name: "sonarr_exporter"
    static_configs:
      - targets: ['docker-media-watcher:9707']
  - job_name: "radarr_exporter"
    static_configs:
      - targets: ['docker-media-watcher:9708']
  - job_name: "lidarr_exporter"
    static_configs:
      - targets: ['docker-media-watcher:9709']
  - job_name: "tautulli_exporter"
    static_configs:
      - targets: ['docker-media-watcher:9487']
  - job_name: "radarr_4k_exporter"
    static_configs:
      - targets: ['docker-media-watcher:9710']
